### PR TITLE
fix: cookie configuration via helm chart.

### PR DESCRIPTION
**Pull request by farmborough**
fixes gravitee-io/issues#7171

### CODE REVIEW

**Review by leleueri — CHANGES_REQUESTED** [review]
Don't think it is useful to change this as default values are managed into the code.
Commented entries into the file are mainly for documentation purpose.

**Comment by farmborough** [comment]
> Don't think it is useful to change this as default values are managed into the code. Commented entries into the file are mainly for documentation purpose.

`

**Comment by farmborough** [comment]
> Don't think it is useful to change this as default values are managed into the code. Commented entries into the file are mainly for documentation purpose.

Was the idea to add this to the values.yml in gravitee-io/helm-chart?

**Comment by leleueri** [comment]
> Was the idea to add this to the values.yml in gravitee-io/helm-chart?

I was going to edit my previous message when I saw your answer.
The change has to be made into the helm-charts project: https://github.com/gravitee-io/helm-charts

You have to update the GW and REST API templates to manage cookie settings:

* https://github.com/gravitee-io/helm-charts/blob/master/am/templates/api/api-configmap.yaml
* https://github.com/gravitee-io/helm-charts/blob/master/am/templates/gateway/gateway-configmap.yaml

**Comment by farmborough** [comment]
Closing this with reference to Eric's comments - work needs to be on helm-chart repo.

**Pull request closed without merging**
