### PR TITLE
chore: remove unused ldap dependency

### PR DESCRIPTION
**Pull request by mstasgravitee**
## :id: Reference related issue. 
https://gravitee.atlassian.net/browse/AM-196

## :man: :woman:@mentions of the person or team responsible for reviewing proposed changes

This is a nice example: https://github.com/gravitee-io/gravitee-access-management/pull/1822

### CODE REVIEW

**Review by leleueri — COMMENTED** [review]
Though: which part of AM is using ldaptive outside of the LDAP and Kerberos IDP  ?

**Comment by mstasgravitee** [comment]
> **question**: which part of AM is using ldaptive outside of the LDAP and Kerberos IDP ?

It is not used outside of these plugins. If you are sure we can safely remove them I can update the PR.

**Comment by leleueri** [comment]
> > **question**: which part of AM is using ldaptive outside of the LDAP and Kerberos IDP ?
> 
> It is not used outside of these plugins. If you are sure we can safely remove them I can update the PR.

IMO, it is safe to remove it if ldaptive is part of the runtime libe embedded into the LDAP & Kerberos plugin

**Comment by mstasgravitee** [comment]
> > > **question**: which part of AM is using ldaptive outside of the LDAP and Kerberos IDP ?
> > 
> > 
> > It is not used outside of these plugins. If you are sure we can safely remove them I can update the PR.
> 
> IMO, it is safe to remove it if ldaptive is part of the runtime libe embedded into the LDAP & Kerberos plugin

removed

**Review by leleueri — APPROVED** [review]

**Pull request merged**
